sudo: false
language: node_js
node_js:
  - '4'
  - '6'
  - '7'
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
  except:
    - /^v\d+\.\d+\.\d+$/
before_script:
  - npm run ci:before
script:
  - npm run ci:script
after_success:
  - npm run ci:after